version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - backend_data:/app/data
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - SECRET_KEY=docker-compose-secret-key-change-me-in-production
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend
      - DATABASE_URL=sqlite:///db.sqlite3
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/api/')"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules # Don't override node_modules with host directory
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

volumes:
  backend_data: 