# Generated by Django 5.0.3 on 2025-03-19 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EngineeringParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Patent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patent_number", models.CharField(max_length=50, unique=True)),
                ("title", models.CharField(max_length=500)),
                ("abstract", models.TextField()),
                ("filing_date", models.DateField()),
                ("publication_date", models.DateField()),
                ("inventors", models.TextField()),
                ("assignee", models.CharField(max_length=500)),
                (
                    "pdf_file",
                    models.FileField(blank=True, null=True, upload_to="patents/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrizPrinciple",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("examples", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="PatentAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("analysis_date", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "improving_parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patent_improvements",
                        to="patent_api.engineeringparameter",
                    ),
                ),
                (
                    "patent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="patent_api.patent",
                    ),
                ),
                (
                    "worsening_parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patent_worsenings",
                        to="patent_api.engineeringparameter",
                    ),
                ),
                (
                    "applied_principles",
                    models.ManyToManyField(
                        related_name="patent_applications",
                        to="patent_api.trizprinciple",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PatentCitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("citation_type", models.CharField(max_length=50)),
                (
                    "cited_patent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citations_received",
                        to="patent_api.patent",
                    ),
                ),
                (
                    "citing_patent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citations_made",
                        to="patent_api.patent",
                    ),
                ),
            ],
            options={
                "unique_together": {("citing_patent", "cited_patent")},
            },
        ),
        migrations.CreateModel(
            name="ContradictionMatrix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "improving_parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="improving_contradictions",
                        to="patent_api.engineeringparameter",
                    ),
                ),
                (
                    "worsening_parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worsening_contradictions",
                        to="patent_api.engineeringparameter",
                    ),
                ),
                ("principles", models.ManyToManyField(to="patent_api.trizprinciple")),
            ],
            options={
                "unique_together": {("improving_parameter", "worsening_parameter")},
            },
        ),
    ]
