# Generated by Django 5.0.3 on 2025-03-20 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patent_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patent",
            name="pdf_file_name",
            field=models.CharField(
                blank=True,
                help_text="Original filename of the uploaded PDF",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patent",
            name="upload_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="patent",
            name="pdf_file",
            field=models.URLField(
                blank=True,
                help_text="URL to the patent PDF file in storage",
                max_length=500,
                null=True,
            ),
        ),
    ]
